-- MySQL Script generated by MySQL Workbench
-- Fri Oct 30 20:16:02 2015
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema product_management
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `product_management` ;
CREATE SCHEMA IF NOT EXISTS `product_management` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `product_management` ;

-- -----------------------------------------------------
-- Table `product_management`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product_management`.`category` ;

CREATE TABLE IF NOT EXISTS `product_management`.`category` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `category_id` BIGINT UNSIGNED NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `name` (`name` ASC),
  INDEX `fk_category_category1_idx` (`category_id` ASC),
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `product_management`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `product_management`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `product_management`.`product` ;

CREATE TABLE IF NOT EXISTS `product_management`.`product` (
  `id` BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(100) NOT NULL,
  `price` DECIMAL(10,2) NOT NULL,
  `available` TINYINT(1) NOT NULL,
  `category_id` BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`, `category_id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `name` (`name` ASC),
  INDEX `available` (`available` ASC),
  INDEX `fk_product_category_idx` (`category_id` ASC),
  INDEX `description` (`description` ASC),
  CONSTRAINT `fk_product_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `product_management`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
